spring.application.name=netask
spring.datasource.url=jdbc:postgresql://localhost:5432/order_sys
spring.datasource.username=abc
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

