spring.application.name=netask
spring.datasource.url=jdbc:postgresql://localhost:5432/order_sys
spring.datasource.username=shop_user
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

